[buildPlans.IosevkaProMono]
family = "Iosevka Pro Mono"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaProMono.variants]
  inherits = "ss09"

    [buildPlans.IosevkaProMono.variants.design]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProMono.variants.italic]
    f = "extended"
    g = "single-storey-serifless"
    k = "cursive-serifless"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProMono.variants.oblique]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaProMono.ligations]
  inherits = "dlig"

[buildPlans.IosevkaProMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaProMono.widths.Extended]
shape = 720
menu = 7
css = "expanded"
[buildPlans.IosevkaProSans]
family = "Iosevka Pro Sans"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaProSans.variants]
  inherits = "ss09"

    [buildPlans.IosevkaProSans.variants.design]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProSans.variants.italic]
    f = "extended"
    g = "single-storey-serifless"
    k = "cursive-serifless"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProSans.variants.oblique]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaProSans.ligations]
  inherits = "dlig"

[buildPlans.IosevkaProSans.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaProSans.widths.Extended]
shape = 720
menu = 7
css = "expanded"
[buildPlans.IosevkaProSerif]
family = "Iosevka Pro Serif"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaProSerif.variants]
  inherits = "ss09"

    [buildPlans.IosevkaProSerif.variants.design]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProSerif.variants.italic]
    f = "extended"
    g = "single-storey-serifless"
    k = "cursive-serifless"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaProSerif.variants.oblique]
    g = "double-storey-open"
    punctuation-dot = "square"
    braille-dot = "square"
    ellipsis-density = "normal"
    asterisk = "hex-low"
    at = "fourfold"
    dollar = "interrupted"
    percent = "dots"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaProSerif.ligations]
  inherits = "dlig"

[buildPlans.IosevkaProSerif.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaProSerif.widths.Extended]
shape = 720
menu = 7
css = "expanded"
